import pytest
from page_objects.__init__ import Pages

@pytest.fixture
def pages(page): 
    return Pages(page)

def test_our_digital_service_heading_present(pages):
    pages.home.goto("https://dhcw.nhs.wales")
    pages.home.upperribbon.click_navigation_option("Our Digital Services")
    pages.our_digital_services.assert_our_digital_services_heading_is_present()

def test_on_default_page_all_services_listed(pages):
    pages.our_digital_services.goto("https://dhcw.nhs.wales/product-directory/our-digital-services")
    pages.our_digital_services.assert_our_digital_services_heading_is_present()
    pages.our_digital_services.assert_digital_service_is_visible("Child Health")
    pages.our_digital_services.assert_digital_service_is_visible("Choose Pharmacy")
    pages.our_digital_services.assert_digital_service_is_visible("Connecting Care")
    pages.our_digital_services.assert_digital_service_is_visible("Dental Access Portal")
    pages.our_digital_services.assert_digital_service_is_visible("Dental e-Referrals")
    pages.our_digital_services.assert_digital_service_is_visible("Electronic Test Requesting in GP Practices")
    pages.our_digital_services.assert_digital_service_is_visible("My A&E Live")
    pages.our_digital_services.assert_digital_service_is_visible("My Health Online")
    pages.our_digital_services.assert_digital_service_is_visible("Patient Access")
    pages.our_digital_services.assert_digital_service_is_visible("Primary Care Electronic Prescription Service")
    pages.our_digital_services.assert_digital_service_is_visible("Secondary Care electronic Prescribing and Medicines Administration")
    pages.our_digital_services.assert_digital_service_is_visible("Shared Medicines Record")
    pages.our_digital_services.assert_digital_service_is_visible("Welsh Clinical Portal")
    pages.our_digital_services.assert_digital_service_is_visible("Welsh GP Record")
    pages.our_digital_services.assert_digital_service_is_visible("Welsh Intensive Care Information System")
    pages.our_digital_services.assert_digital_service_is_visible("Welsh Nursing Care Record (WCNR)")


def test_digital_services_visible_when_hospitals_and_clinics_selected(pages):
    pages.home.goto("https://dhcw.nhs.wales")
    pages.home.upperribbon.click_navigation_option("Product directory")
    new_tab = pages.product_directory.click_digital_service_category("Hospitals and clinics")
    new_window = Pages(new_tab)
    new_window.our_digital_services.assert_digital_service_is_visible("My A&E Live")
    new_window.our_digital_services.assert_digital_service_is_visible("Patient Access")
    new_window.our_digital_services.assert_digital_service_is_visible("Secondary Care electronic Prescribing and Medicines Administration")
    new_window.our_digital_services.assert_digital_service_is_visible("Welsh Clinical Portal")
    new_window.our_digital_services.assert_digital_service_is_visible("Welsh Intensive Care Information System") 
    new_window.our_digital_services.assert_digital_service_is_hidden("Child Health")
    new_window.our_digital_services.assert_digital_service_is_hidden("Choose Pharmacy")
    new_window.our_digital_services.assert_digital_service_is_hidden("Connecting Care")
    new_window.our_digital_services.assert_digital_service_is_hidden("Dental Access Portal")
    new_window.our_digital_services.assert_digital_service_is_hidden("Dental e-Referrals")
    new_window.our_digital_services.assert_digital_service_is_hidden("Electronic Test Requesting in GP Practices")
    new_window.our_digital_services.assert_digital_service_is_hidden("My Health Online")
    new_window.our_digital_services.assert_digital_service_is_hidden("Primary Care Electronic Prescription Service")
    new_window.our_digital_services.assert_digital_service_is_hidden("Shared Medicines Record")
    new_window.our_digital_services.assert_digital_service_is_hidden("Welsh GP Record")
    new_window.our_digital_services.assert_digital_service_is_hidden("Welsh Nursing Care Record (WCNR)")

def test_digital_services_visible_when_gp_and_community_care_selected(pages):
    pages.home.goto("https://dhcw.nhs.wales")
    pages.home.upperribbon.click_navigation_option("Product directory")
    new_tab = pages.product_directory.click_digital_service_category("GP and community care")
    new_window = Pages(new_tab)
    new_window.our_digital_services.assert_digital_service_is_visible("Child Health")
    new_window.our_digital_services.assert_digital_service_is_visible("Connecting Care")
    new_window.our_digital_services.assert_digital_service_is_visible("Electronic Test Requesting in GP Practices")
    new_window.our_digital_services.assert_digital_service_is_visible("Primary Care Electronic Prescription Service")
    new_window.our_digital_services.assert_digital_service_is_visible("Welsh GP Record")
    new_window.our_digital_services.assert_digital_service_is_hidden("My A&E Live")
    new_window.our_digital_services.assert_digital_service_is_hidden("Patient Access")
    new_window.our_digital_services.assert_digital_service_is_hidden("Secondary Care electronic Prescribing and Medicines Administration")
    new_window.our_digital_services.assert_digital_service_is_hidden("Welsh Clinical Portal")
    new_window.our_digital_services.assert_digital_service_is_hidden("Welsh Intensive Care Information System") 
    new_window.our_digital_services.assert_digital_service_is_hidden("Choose Pharmacy")
    new_window.our_digital_services.assert_digital_service_is_hidden("Dental Access Portal")
    new_window.our_digital_services.assert_digital_service_is_hidden("Dental e-Referrals")
    new_window.our_digital_services.assert_digital_service_is_hidden("My Health Online")
    new_window.our_digital_services.assert_digital_service_is_hidden("Shared Medicines Record")
    new_window.our_digital_services.assert_digital_service_is_hidden("Welsh Nursing Care Record (WCNR)")


def test_digital_services_visible_when_medicines_and_pharmacy_selected(pages):
    pages.home.goto("https://dhcw.nhs.wales")
    pages.home.upperribbon.click_navigation_option("Product directory")
    new_tab = pages.product_directory.click_digital_service_category("Medicines and pharmacy")
    new_window = Pages(new_tab)
    new_window.our_digital_services.assert_digital_service_is_visible("Primary Care Electronic Prescription Service")
    new_window.our_digital_services.assert_digital_service_is_visible("Patient Access")
    new_window.our_digital_services.assert_digital_service_is_visible("Choose Pharmacy")
    new_window.our_digital_services.assert_digital_service_is_visible("Secondary Care electronic Prescribing and Medicines Administration")
    new_window.our_digital_services.assert_digital_service_is_visible("Welsh Clinical Portal")
    new_window.our_digital_services.assert_digital_service_is_visible("Welsh GP Record")
    new_window.our_digital_services.assert_digital_service_is_hidden("Welsh Intensive Care Information System") 
    new_window.our_digital_services.assert_digital_service_is_hidden("Child Health")
    new_window.our_digital_services.assert_digital_service_is_hidden("My A&E Live")
    new_window.our_digital_services.assert_digital_service_is_hidden("Connecting Care")
    new_window.our_digital_services.assert_digital_service_is_hidden("Dental Access Portal")
    new_window.our_digital_services.assert_digital_service_is_hidden("Dental e-Referrals")
    new_window.our_digital_services.assert_digital_service_is_hidden("Electronic Test Requesting in GP Practices")
    new_window.our_digital_services.assert_digital_service_is_hidden("My Health Online")
    new_window.our_digital_services.assert_digital_service_is_hidden("Shared Medicines Record")
    new_window.our_digital_services.assert_digital_service_is_hidden("Welsh Nursing Care Record (WCNR)")

def test_digital_services_visible_when_urgent_and_emergency_care_selected(pages):
    pages.home.goto("https://dhcw.nhs.wales")
    pages.home.upperribbon.click_navigation_option("Product directory")
    new_tab = pages.product_directory.click_digital_service_category("Urgent and Emergency Care")
    new_window = Pages(new_tab)
    new_window.our_digital_services.assert_digital_service_is_visible("My A&E Live")
    new_window.our_digital_services.assert_digital_service_is_hidden("Patient Access")
    new_window.our_digital_services.assert_digital_service_is_hidden("Secondary Care electronic Prescribing and Medicines Administration")
    new_window.our_digital_services.assert_digital_service_is_hidden("Welsh Clinical Portal")
    new_window.our_digital_services.assert_digital_service_is_hidden("Welsh Intensive Care Information System") 
    new_window.our_digital_services.assert_digital_service_is_hidden("Child Health")
    new_window.our_digital_services.assert_digital_service_is_hidden("Choose Pharmacy")
    new_window.our_digital_services.assert_digital_service_is_hidden("Connecting Care")
    new_window.our_digital_services.assert_digital_service_is_hidden("Dental Access Portal")
    new_window.our_digital_services.assert_digital_service_is_hidden("Dental e-Referrals")
    new_window.our_digital_services.assert_digital_service_is_hidden("Electronic Test Requesting in GP Practices")
    new_window.our_digital_services.assert_digital_service_is_hidden("My Health Online")
    new_window.our_digital_services.assert_digital_service_is_hidden("Primary Care Electronic Prescription Service")
    new_window.our_digital_services.assert_digital_service_is_hidden("Shared Medicines Record")
    new_window.our_digital_services.assert_digital_service_is_hidden("Welsh GP Record")
    new_window.our_digital_services.assert_digital_service_is_hidden("Welsh Nursing Care Record (WCNR)")

def test_digital_services_visible_when_diagnostics_department_selected(pages):
    pages.home.goto("https://dhcw.nhs.wales")
    pages.home.upperribbon.click_navigation_option("Product directory")
    new_tab = pages.product_directory.click_digital_service_category("Diagnostics Departments")
    new_window = Pages(new_tab)
    new_window.our_digital_services.assert_digital_service_is_visible("Welsh Clinical Portal")
    new_window.our_digital_services.assert_digital_service_is_hidden("My A&E Live")
    new_window.our_digital_services.assert_digital_service_is_hidden("Patient Access")
    new_window.our_digital_services.assert_digital_service_is_hidden("Secondary Care electronic Prescribing and Medicines Administration")
    new_window.our_digital_services.assert_digital_service_is_hidden("Welsh Intensive Care Information System") 
    new_window.our_digital_services.assert_digital_service_is_hidden("Child Health")
    new_window.our_digital_services.assert_digital_service_is_hidden("Choose Pharmacy")
    new_window.our_digital_services.assert_digital_service_is_hidden("Connecting Care")
    new_window.our_digital_services.assert_digital_service_is_hidden("Dental Access Portal")
    new_window.our_digital_services.assert_digital_service_is_hidden("Dental e-Referrals")
    new_window.our_digital_services.assert_digital_service_is_hidden("Electronic Test Requesting in GP Practices")
    new_window.our_digital_services.assert_digital_service_is_hidden("My Health Online")
    new_window.our_digital_services.assert_digital_service_is_hidden("Primary Care Electronic Prescription Service")
    new_window.our_digital_services.assert_digital_service_is_hidden("Shared Medicines Record")
    new_window.our_digital_services.assert_digital_service_is_hidden("Welsh GP Record")
    new_window.our_digital_services.assert_digital_service_is_hidden("Welsh Nursing Care Record (WCNR)")


def test_digital_services_visible_when_the_nhs_wales_app_selected(pages):
    pages.home.goto("https://dhcw.nhs.wales")
    pages.home.upperribbon.click_navigation_option("Product directory")
    new_tab = pages.product_directory.click_digital_service_category("The NHS Wales App")
    new_window = Pages(new_tab)
    new_window.nhs_wales_app_help_support.assert_heading_is_present()